In [10]:
import pandas as pd
#2010-01-01 ~ 2021-06 까지 누계자료
kto_data = pd.read_excel(
            "data/방한 외래관광객_20210824.xlsx"
            ,header = 1
            ,usecols = "A:P"
            ,skipfooter = 0
)

In [11]:
kto_data.head(50)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,인원수,증감률(%),인원수.1,증감률(%).1,인원수.2,증감률(%).2,인원수.3,증감률(%).3,인원수.4,증감률(%).4,인원수.5,증감률(%).5
0,2010,01,아시아,중국,91252,-1.89,40425.0,-7.30,11930.0,22.33,55.0,66.67,2751.0,-5.17,36091.0,-1.70
1,NaN,NaN,NaN,일본,209184,-12.04,202825.0,-11.93,1750.0,-25.63,89.0,-18.35,549.0,8.07,3971.0,-12.59
2,NaN,NaN,NaN,대만,36399,-2.74,35788.0,-2.63,41.0,20.59,17.0,-37.04,37.0,-44.78,516.0,-4.97
3,NaN,NaN,NaN,홍콩,14545,-42.30,13874.0,-43.16,55.0,57.14,NaN,NaN,21.0,133.33,595.0,-21.09
4,NaN,NaN,NaN,마카오,554,-41.99,554.0,-41.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,필리핀,21214,-2.79,3984.0,13.83,219.0,69.77,104.0,-5.45,87.0,14.47,16820.0,-6.60
6,NaN,NaN,NaN,인도네시아,5061,-12.71,1840.0,-27.59,327.0,100.61,3.0,-70.00,65.0,54.76,2826.0,-7.10
7,NaN,NaN,NaN,태국,17814,27.73,13374.0,48.77,39.0,21.88,13.0,-18.75,53.0,12.77,4335.0,-10.84
8,NaN,NaN,NaN,베트남,4515,-11.44,1384.0,-3.49,284.0,73.17,21.0,600.00,150.0,45.63,2676.0,-21.15
9,NaN,NaN,NaN,인도,6026,9.13,1646.0,-9.36,1387.0,46.31,7.0,16.67,68.0,36.00,2918.0,7.99
10,NaN,NaN,NaN,말레이시아,4559,-32.10,3292.0,-37.02,61.0,154.17,0.0,-100.00,49.0,11.36,1157.0,-18.41
11,NaN,NaN,NaN,싱가포르,5368,-16.36,4201.0,-12.30,120.0,79.10,3.0,200.00,27.0,92.86,1017.0,-34.22
12,NaN,NaN,NaN,몽골,3324,4.99,2333.0,24.89,234.0,-16.73,6.0,100.00,197.0,1.03,554.0,-32.36
13,NaN,NaN,NaN,우즈베키스탄,1280,1.91,190.0,27.52,293.0,-23.50,17.0,750.00,40.0,-16.67,740.0,9.79
14,NaN,NaN,NaN,미얀마,4594,10.35,630.0,11.31,18.0,5.88,54.0,NaN,10.0,233.33,3882.0,8.53
15,NaN,NaN,NaN,GCC,430,95.45,223.0,82.79,134.0,152.83,0.0,-100.00,18.0,50.00,55.0,83.33
16,NaN,NaN,NaN,카자흐스탄,419,0.72,238.0,0.42,48.0,23.08,4.0,300.00,22.0,NaN,107.0,-8.55
17,NaN,NaN,NaN,터키,969,45.71,472.0,31.48,15.0,-34.78,2.0,NaN,15.0,114.29,465.0,69.71
18,NaN,NaN,NaN,캄보디아,280,-35.93,102.0,-28.17,22.0,100.00,NaN,NaN,25.0,127.27,131.0,-52.01
19,NaN,NaN,NaN,스리랑카,648,-23.40,39.0,-13.33,28.0,12.00,2.0,100.00,13.0,8.33,566.0,-25.82
20,NaN,NaN,NaN,방글라데시,710,44.90,86.0,2.38,84.0,-4.55,9.0,125.00,42.0,40.00,489.0,72.18
21,NaN,NaN,NaN,파키스탄,714,11.39,70.0,-24.73,200.0,-14.89,1.0,-50.00,41.0,64.00,402.0,40.56
22,NaN,NaN,NaN,이스라엘,856,24.24,792.0,28.57,11.0,10.00,NaN,NaN,NaN,NaN,53.0,-15.87
23,NaN,NaN,NaN,이란,598,34.08,69.0,-15.85,309.0,48.56,0.0,-100.00,3.0,NaN,217.0,42.76
24,NaN,NaN,NaN,아시아 기타,1732,16.40,700.0,77.66,629.0,20.73,14.0,-22.22,56.0,55.56,333.0,-35.84
25,NaN,NaN,아시아 소계,NaN,433045,-8.77,329131.0,-10.82,18238.0,16.95,421.0,19.26,4339.0,1.74,80916.0,-5.20
26,NaN,NaN,아메리카,미국,43065,0.27,26943.0,-3.37,1195.0,-17.01,2145.0,-4.20,135.0,-10.00,12647.0,12.55
27,NaN,NaN,NaN,캐나다,8776,0.91,4912.0,1.78,96.0,-23.20,4.0,-20.00,21.0,5.00,3743.0,0.59
28,NaN,NaN,NaN,브라질,765,2.27,459.0,15.91,46.0,-4.17,1.0,-50.00,11.0,37.50,248.0,-15.65
29,NaN,NaN,NaN,멕시코,379,-0.52,252.0,-7.69,29.0,38.10,1.0,NaN,4.0,-69.23,93.0,27.40
30,NaN,NaN,NaN,아메리카 기타,854,-5.95,501.0,-11.17,25.0,-10.71,8.0,-33.33,29.0,38.10,291.0,2.83
31,NaN,NaN,아메리카 소계,NaN,53839,0.29,33067.0,-2.58,1391.0,-16.31,2159.0,-4.43,200.0,-5.66,17022.0,9.06
32,NaN,NaN,유럽,러시아,10873,-7.90,4861.0,-3.07,505.0,19.95,15.0,-6.25,83.0,-1.19,5409.0,-13.73
33,NaN,NaN,NaN,영국,7521,-8.56,5746.0,-9.98,383.0,-6.13,4.0,100.00,20.0,185.71,1368.0,-4.00
34,NaN,NaN,NaN,독일,7643,-5.62,5838.0,-5.46,255.0,2.00,24.0,4.35,68.0,100.00,1458.0,-9.78
35,NaN,NaN,NaN,프랑스,4666,1.13,3019.0,6.57,343.0,-13.16,44.0,-8.33,115.0,49.35,1145.0,-9.20
36,NaN,NaN,NaN,이탈리아,1376,-5.17,1157.0,-7.44,40.0,-4.76,12.0,NaN,12.0,NaN,155.0,14.81
37,NaN,NaN,NaN,네덜란드,1722,6.56,1205.0,6.35,47.0,-2.08,1.0,NaN,20.0,150.00,449.0,5.15
38,NaN,NaN,NaN,우크라이나,1936,8.58,386.0,87.38,29.0,-6.45,0.0,-100.00,6.0,-33.33,1515.0,-1.37
39,NaN,NaN,NaN,스페인,698,11.50,542.0,17.32,29.0,NaN,11.0,37.50,8.0,-20.00,108.0,-7.69
40,NaN,NaN,NaN,루마니아,533,11.27,142.0,-17.92,12.0,-40.00,NaN,NaN,9.0,12.50,370.0,33.09
41,NaN,NaN,NaN,노르웨이,946,-8.24,517.0,-16.61,274.0,-6.80,NaN,NaN,6.0,NaN,149.0,34.23
42,NaN,NaN,NaN,스웨덴,849,15.98,579.0,7.42,63.0,-18.18,5.0,-50.00,17.0,54.55,185.0,94.74
43,NaN,NaN,NaN,폴란드,848,-0.35,378.0,0.27,29.0,-12.12,NaN,NaN,10.0,-33.33,431.0,1.17
44,NaN,NaN,NaN,스위스,626,-0.79,512.0,-0.58,30.0,114.29,NaN,NaN,7.0,133.33,77.0,-22.22
45,NaN,NaN,NaN,포르투갈,310,-45.61,256.0,-51.15,9.0,28.57,NaN,NaN,1.0,NaN,44.0,15.79
46,NaN,NaN,NaN,오스트리아,605,2.89,440.0,-0.23,13.0,62.50,2.0,-33.33,9.0,NaN,141.0,11.02
47,NaN,NaN,NaN,핀란드,535,-17.82,376.0,-14.93,16.0,-46.67,NaN,NaN,12.0,-14.29,131.0,-20.61
48,NaN,NaN,NaN,벨기에,460,9.26,322.0,14.59,25.0,-7.41,1.0,NaN,8.0,700.00,104.0,-7.14
49,NaN,NaN,NaN,크로아티아,485,-34.28,166.0,-23.85,20.0,-4.76,NaN,NaN,1.0,NaN,298.0,-40.16