In [1]:
import pandas as pd

In [2]:
sample01 = pd.read_excel("data/2014년 성남벤처넷 성남기업 회원현황.xls"
                        , header = 0
                        #, skipfooter = 1
                        , usecols = "a:r")
sample01.head()

,회사명,대표자,회사전화,회사주소,우편번호,주요취급품목,업종,회사설립일,홈페이지,HS코드,벤처기업인증여부,이노비즈인증여부,기업부설연구소여부,특허건수,실용신안건수,의장등록건수,기타 국내외 인증 건수
0,1492피앤씨애드,유희숙,070-4207-9707,성남시 분당구 판교로 253 판교이노밸리 B동 901호,463400,"소프트웨어개발 및 공급업, 모바일콘텐츠",NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,올그린티앤지,하명호,031-737-2091,경기도 성남시 중원구 상대원동 311-3 우림라이온스밸리 1116호,462120,건강식품,NaN,2008-10-01,www.allgreentng.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,바이오버드,김종탁,031-628-0800,경기도 성남시 분당구 삼평동 694-1 코이라바이오파크 B-904,463400,"Aposcan kit, BFGF",NaN,2000-03-28,www.biobud.com,NaN,Y,Y,NaN,NaN,NaN,NaN,NaN
3,지엘바이오,지경민,070-4349-1195,성남시 수정구 신흥동 5180번지 샤르망 1층,NaN,"공산품, oem화장품, 산지협력 특산품 등 ?",NaN,2011-05-24,www.greenbiosys.com,NaN,Y,NaN,NaN,2.0,9.0,NaN,2.0
4,인앤시스,안근백,070-7817-5273,경기 성남시 분당구 정자동 54-1 403,NaN,차량용 네비게이션,NaN,2011-01-20,www.innsys.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
sample01.tail()

,회사명,대표자,회사전화,회사주소,우편번호,주요취급품목,업종,회사설립일,홈페이지,HS코드,벤처기업인증여부,이노비즈인증여부,기업부설연구소여부,특허건수,실용신안건수,의장등록건수,기타 국내외 인증 건수
4502,실리콘투,김성운,031-783-241,경기 성남시 분당구 정자동 파크뷰 오피스타워 1002 1003,463863,"반도체, 메모리, USB 외",기타 전자부품 제조업,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4503,위드콘,안복근,031-737-6761,경기 성남시 중원구 상대원동 중일 아인스프라츠 503호,462120,시설물 유지 보수 보강,NaN,NaT,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN
4504,딱따구리,박정호,070-8200-3954,경기 성남시 중원구 상대원동 442-5쌍용IT타워 B동 602호,462120,인터넷라디오,방송장비 제조업,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4505,종합상사진영,박성승,031-745-4277,경기 성남시 중원구 상대원1동 진영수출포장,462811,"스폰지가공생산,박스,포장자재",NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4506,벨리시모,전정영,031-726-4048,경기 성남시 분당구 정자동 32-11 지층1호,463848,블라인드 원단,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
sample01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4507 entries, 0 to 4506
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   회사명           4506 non-null   object
 1   대표자           3822 non-null   object
 2   회사전화          3003 non-null   object
 3   회사주소          4503 non-null   object
 4   우편번호          4288 non-null   object
 5   주요취급품목        2474 non-null   object
 6   업종            1556 non-null   object
 7   회사설립일         1257 non-null   datetime64[ns]
 8   홈페이지          1043 non-null   object
 9   HS코드          82 non-null     float64
 10  벤처기업인증여부      298 non-null    object
 11  이노비즈인증여부      158 non-null    object
 12  기업부설연구소여부     558 non-null    object
 13  특허건수          327 non-null    float64
 14  실용신안건수        92 non-null     float64
 15  의장등록건수        66 non-null     float64
 16  기타 국내외 인증 건수  177 non-null    float64
dtypes: datetime64[ns](1), float64(5), object(11)
memory usage: 598.7+ KB

In [31]:
sample01.describe()

               HS코드        특허건수     실용신안건수     의장등록건수  기타 국내외 인증 건수
count  8.200000e+01  327.000000  92.000000  66.000000    177.000000
mean   2.983529e+09    4.813456   2.902174   4.424242      7.327684
std    3.769708e+09    6.693010   3.972598   7.134015     20.307437
min    0.000000e+00    0.000000   0.000000   0.000000      0.000000
25%    8.532500e+03    1.000000   1.000000   1.000000      2.000000
50%    8.496263e+07    2.000000   2.000000   2.000000      3.000000
75%    8.392150e+09    5.000000   3.000000   3.750000      6.000000
max    9.503003e+09   49.000000  34.000000  41.000000    250.000000

In [32]:
sample01

,회사명,대표자,회사전화,회사주소,우편번호,주요취급품목,업종,회사설립일,홈페이지,HS코드,벤처기업인증여부,이노비즈인증여부,기업부설연구소여부,특허건수,실용신안건수,의장등록건수,기타 국내외 인증 건수
0,1492피앤씨애드,유희숙,070-4207-9707,성남시 분당구 판교로 253 판교이노밸리 B동 901호,463400,"소프트웨어개발 및 공급업, 모바일콘텐츠",NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,올그린티앤지,하명호,031-737-2091,경기도 성남시 중원구 상대원동 311-3 우림라이온스밸리 1116호,462120,건강식품,NaN,2008-10-01,www.allgreentng.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,바이오버드,김종탁,031-628-0800,경기도 성남시 분당구 삼평동 694-1 코이라바이오파크 B-904,463400,"Aposcan kit, BFGF",NaN,2000-03-28,www.biobud.com,NaN,Y,Y,NaN,NaN,NaN,NaN,NaN
3,지엘바이오,지경민,070-4349-1195,성남시 수정구 신흥동 5180번지 샤르망 1층,NaN,"공산품, oem화장품, 산지협력 특산품 등 ?",NaN,2011-05-24,www.greenbiosys.com,NaN,Y,NaN,NaN,2.0,9.0,NaN,2.0
4,인앤시스,안근백,070-7817-5273,경기 성남시 분당구 정자동 54-1 403,NaN,차량용 네비게이션,NaN,2011-01-20,www.innsys.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4502,실리콘투,김성운,031-783-241,경기 성남시 분당구 정자동 파크뷰 오피스타워 1002 1003,463863,"반도체, 메모리, USB 외",기타 전자부품 제조업,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4503,위드콘,안복근,031-737-6761,경기 성남시 중원구 상대원동 중일 아인스프라츠 503호,462120,시설물 유지 보수 보강,NaN,NaT,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN
4504,딱따구리,박정호,070-8200-3954,경기 성남시 중원구 상대원동 442-5쌍용IT타워 B동 602호,462120,인터넷라디오,방송장비 제조업,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4505,종합상사진영,박성승,031-745-4277,경기 성남시 중원구 상대원1동 진영수출포장,462811,"스폰지가공생산,박스,포장자재",NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4506,벨리시모,전정영,031-726-4048,경기 성남시 분당구 정자동 32-11 지층1호,463848,블라인드 원단,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
sample01["회사전화"]

0       070-4207-9707
1        031-737-2091
2        031-628-0800
3       070-4349-1195
4       070-7817-5273
            ...
4502      031-783-241
4503     031-737-6761
4504    070-8200-3954
4505     031-745-4277
4506     031-726-4048
Name: 회사전화, Length: 4507, dtype: object

In [35]:
condition = ( sample01["회사설립일"] > "2010-01-01" )
condition

0       False
1       False
2       False
3        True
4        True
        ...
4502    False
4503    False
4504    False
4505    False
4506    False
Name: 회사설립일, Length: 4507, dtype: bool

In [36]:
sample01[condition]

,회사명,대표자,회사전화,회사주소,우편번호,주요취급품목,업종,회사설립일,홈페이지,HS코드,벤처기업인증여부,이노비즈인증여부,기업부설연구소여부,특허건수,실용신안건수,의장등록건수,기타 국내외 인증 건수
3,지엘바이오,지경민,070-4349-1195,성남시 수정구 신흥동 5180번지 샤르망 1층,NaN,"공산품, oem화장품, 산지협력 특산품 등 ?",NaN,2011-05-24,www.greenbiosys.com,NaN,Y,NaN,NaN,2.0,9.0,NaN,2.0
4,인앤시스,안근백,070-7817-5273,경기 성남시 분당구 정자동 54-1 403,NaN,차량용 네비게이션,NaN,2011-01-20,www.innsys.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,하비투스,반호영,070-4235-0215,경기도 성남시 분당구 서현동 263 모바일게임센터 1312호,463824,"모바일용 소셜네트워크게임 개발 및 서비스, 뇌졸증 환자 재활 치료를 위한 E-Glo...",NaN,2011-02-15,www.habitus.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,리얼씨엔아이,이맹호,070-7433-8669,성남시 분당구 야탑동 366-1,NaN,소프트웨어,NaN,2012-03-07,www.realcni.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,연팩토리,황지연,031-732-9931,중원구 상대원동 138-12 노벨테크노타워 502,NaN,"유리아트(트로피, 소품, 쥬얼리) 제조",NaN,2011-02-28,www.glassyeon.co.kr,NaN,Y,NaN,Y,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4180,덴도무시,이광희,NaN,경기도 용인시 기흥구 죽전로15번길 8-7 1189 12,446857,NaN,"기타 섬유, 직물 및 의복액세서리 소매업",2012-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4182,페이지원테크,민경일,070-4633-2284,"경기도 성남시 분당구 판교로 253 B-401(삼평동,판교이노밸리)",463400,NaN,소프트웨어 개발 및 공급업,2012-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4472,세베토,박종광,031-749-9145,경기 성남시 중원구 여수동 136-1 3층,462100,"신발, 친환경세제, 이미용제품",NaN,2010-04-21,33pakpak.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4483,셀리언트,김완호,070-4191-7763,경기 성남시 분당구 금곡동 165 천사의 도시 2차 517,463805,"통신기기, Mobile Wi-Fi AP, Wireless M2M Module",방송장비 제조업,2010-07-05,www.cellient.co.kr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4487,윈스테크넷,김대연,031-622-8600,경기 성남시 분당구 삼평동 633 판교세븐벤처밸리 1동 7층,463400,"SNIPER IPS, SNIPER DDX, SNIPER WAF, SNIPER VF 등","컴퓨터시스템 통합 자문, 구축 및 관리업",2011-01-01,www.wins21.co.kr,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN